In [2]:
import numpy as np

In [ ]:
Question 1

In [6]:
A = np.array([[2,-1],[0,3]])
B = np.array([[1,2],[-3,4]])

#For question 1(a)
print(A+B)

#For question 1(b)
print(A @ B)

#For question 1(c)
print(3*A-2*B)


[[ 3  1]
 [-3  7]]
[[ 5  0]
 [-9 12]]
[[ 4 -7]
 [ 6  1]]


Question 2

In [9]:
#For question 2(a)
det = round(np.linalg.det(A),2)
print(f"The determinant of matrix A is: {det}")

print()
#For question 2(b)
if(not det==0):
    print("Inverse of matrix A exists.")
    inverse = np.linalg.inv(A)
    print("The inverse of the matrix A is:")
    print(inverse)
else:
    print("Inverse of matrix A doesn't exist.")

The determinant of matrix A is: 6.0

Inverse of matrix A exists.
The inverse of the matrix A is:
[[0.5        0.16666667]
 [0.         0.33333333]]


Question 3


In [12]:
C = np.array([[4,1],[-2,1]])
egval,egvec = np.linalg.eig(A)
print(f"The eigen values of matrix A are: {egval}")
print()
print(f"The eigen vectors of matrix A are: {egvec}")

The eigen values of matrix A are: [2. 3.]

The eigen vectors of matrix A are: [[ 1.         -0.70710678]
 [ 0.          0.70710678]]


In [ ]:
Question 4

In [3]:

F = np.array([[4,1.5,100],[6,2.0,150]])
Pr = np.array([[20],[30]])
inverse = np.linalg.pinv(F.T @ F)
B = inverse @ F.T @ Pr
X = np.array([[8,3.0,200]])
price = np.linalg.det(X @ B)
print(f"The price of the car X3 is: {price}")



The price of the car X3 is: 39.999999999998806
